tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/dupes'
tap 'neovim/neovim'
tap 'rcmdnk/file'
tap 'sanemat/font'
cask 'xquartz'
brew 'libyaml'
brew 'openssl@1.1'
brew 'gdbm'
brew 'openssl'
brew 'readline'
brew 'sqlite'
brew 'python'
brew 'ansible'
brew 'autoconf'
brew 'automake'
brew 'libpng'
brew 'freetype'
brew 'fontconfig'
brew 'gettext'
brew 'libffi'
brew 'pcre'
brew 'glib'
brew 'pixman'
brew 'cairo'
brew 'cmake'
brew 'zeromq'
brew 'czmq'
brew 'doxygen'
brew 'flow'
brew 'git'
brew 'jpeg'
brew 'libtiff'
brew 'libtool'
brew 'pkg-config'
brew 'gobject-introspection'
brew 'icu4c'
brew 'harfbuzz'
brew 'pango'
brew 'fontforge'
brew 'gibo'
brew 'go'
brew 'heroku'
brew 'jemalloc'
brew 'libevent'
brew 'libsodium'
brew 'libtermkey'
brew 'libuv'
brew 'libvterm'
brew 'mas'
brew 'msgpack'
brew 'mysql'
brew 'node'
brew 'redis'
brew 'rmtrash'
brew 'tmux'
brew 'tree'
brew 'unibilium'
brew 'utf8proc'
brew 'watchman'
brew 'wget'
brew 'yarn'
brew 'zsh'
brew 'neovim/neovim/neovim'
brew 'sanemat/font/ricty'
cask 'firefox'
cask 'google-chrome'
cask 'google-japanese-ime'
cask 'vagrant'
cask 'virtualbox'
mas 'App Cleaner', id: 1013897218
mas 'Display Menu', id: 549083868
mas 'GarageBand', id: 682658836
mas 'iMovie', id: 408981434
mas 'Keynote', id: 409183694
mas 'Magnet', id: 441258766
mas 'Numbers', id: 409203825
mas 'Pages', id: 409201541
mas 'Skitch', id: 425955336
